query PromotionRunAutoVersioningTrail($id: Int!, $offset: Int!, $size: Int!) {
    promotionRuns(id: $id) {
        autoVersioningTrailPaginated(offset: $offset, size: $size, filter: {onlyEligible: false}) {
            pageInfo {
                nextPage {
                    offset
                    size
                }
            }
            pageItems {
                id
                branch {
                    ...BranchFragment
                }
                configuration {
                    ...AutoVersioningSourceConfigFragment
                }
                rejectionReason
                orderId
            }
        }
    }
}
