#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Provisions the gitlab.com test group, bot and fixture project behind the real
# ontrack-extension-gitlab tests (issue #1826). See the "Testing" section of
# ontrack-extension-gitlab/README.md.
#
#   ontrack-extension-gitlab/scripts/gitlab-test-project.sh
#
# Re-run it to renew the token: Enter keeps every value already captured.

TOTAL_STAGES=11

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
MODULE_DIR=$(dirname "$SCRIPT_DIR")
REPO_ROOT=$(dirname "$MODULE_DIR")
FIXTURE_DIR="$MODULE_DIR/src/test/resources/gitlab-fixture"
README="$MODULE_DIR/README.md"
# Remembers the values between runs, and doubles as an environment file for running the real tests locally.
# Gitignored. It holds the token in clear: keep it on this machine.
ENV_FILE="$REPO_ROOT/.gitlab-test.env"
# The library's gh calls carry no --repo: pin the repository whatever the current remote.
export GH_REPO="yontrack/yontrack"
# gitlab.com only. A self-managed instance is supported by the extension but is not what the tests run against.
API="https://gitlab.com/api/v4"
MAIN_BRANCH="main"

ONTRACK_TEST_EXTENSION_GITLAB_GROUP=""
ONTRACK_TEST_EXTENSION_GITLAB_PROJECT=""
ONTRACK_TEST_EXTENSION_GITLAB_TOKEN=""
ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY=""

SECRETS="ONTRACK_TEST_EXTENSION_GITLAB_GROUP
ONTRACK_TEST_EXTENSION_GITLAB_PROJECT
ONTRACK_TEST_EXTENSION_GITLAB_TOKEN"
EXPIRY_VAR="ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY"

# ── Helpers for these stages ──────────────────────────────────────────────

ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

have_jq() { command -v jq >/dev/null 2>&1; }

# require ask|ask_secret KEY "Prompt" — like ask, but insists on a value.
require() {
  local fn="$1" key="$2" prompt="$3"
  while true; do
    "$fn" "$key" "$prompt"
    [[ -n "${!key}" ]] && return 0
    warn "a value is required"
  done
}

# ask_date KEY "Prompt" — insists on a YYYY-MM-DD date.
ask_date() {
  local key="$1" prompt="$2"
  while true; do
    ask "$key" "$prompt"
    [[ "${!key}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] && return 0
    warn "expected a date as YYYY-MM-DD"
  done
}

# The token goes through curl's stdin config, never its command line, so it doesn't show in `ps`.

# api_status PATH — HTTP status of a GET on the API, as the bot.
api_status() {
  printf 'header = "PRIVATE-TOKEN: %s"\n' "$ONTRACK_TEST_EXTENSION_GITLAB_TOKEN" \
    | curl -sS -K - -o /dev/null -w '%{http_code}' "$API$1" 2>/dev/null || true
}

# api_get PATH — body of a GET on the API, as the bot.
api_get() {
  printf 'header = "PRIVATE-TOKEN: %s"\n' "$ONTRACK_TEST_EXTENSION_GITLAB_TOKEN" \
    | curl -sS -K - "$API$1" 2>/dev/null || true
}

# api_post PATH FILE — body of a POST of the JSON in FILE, as the bot.
api_post() {
  printf 'header = "PRIVATE-TOKEN: %s"\n' "$ONTRACK_TEST_EXTENSION_GITLAB_TOKEN" \
    | curl -sS -K - -X POST -H 'Content-Type: application/json' --data-binary "@$2" "$API$1" 2>/dev/null || true
}

# api_post_status PATH FILE — HTTP status of that POST.
api_post_status() {
  printf 'header = "PRIVATE-TOKEN: %s"\n' "$ONTRACK_TEST_EXTENSION_GITLAB_TOKEN" \
    | curl -sS -K - -o /dev/null -w '%{http_code}' -X POST -H 'Content-Type: application/json' \
        --data-binary "@$2" "$API$1" 2>/dev/null || true
}

# expect EXPECTED "what" COMMAND... — runs COMMAND until it prints EXPECTED, or the human gives up.
expect() {
  local expected="$1" what="$2" actual
  shift 2
  while true; do
    actual=$("$@")
    if [[ "$actual" == "$expected" ]]; then
      ok "$what"
      return 0
    fi
    warn "$what — got '${actual:-nothing}', expected '$expected'"
    note "A wrong value? Answer N, let the wizard finish, and re-run it: Enter keeps the other values."
    if ! confirm "Fixed it in the browser — check again?"; then
      SKIPPED+=("check failed: $what")
      return 0
    fi
  done
}

# full_path — group/project, as GitLab spells it.
full_path() {
  printf '%s/%s' "$ONTRACK_TEST_EXTENSION_GITLAB_GROUP" "$ONTRACK_TEST_EXTENSION_GITLAB_PROJECT"
}

# project_id — the URL-encoded path GitLab takes wherever `:id` appears.
project_id() {
  full_path | sed 's|/|%2F|g'
}

# group_id — same, for the group: a subgroup path carries slashes too.
group_id() {
  printf '%s' "$ONTRACK_TEST_EXTENSION_GITLAB_GROUP" | sed 's|/|%2F|g'
}

# project_field FIELD — one field of the fixture project, or 'unavailable' when GitLab does not report it.
project_field() {
  local body
  body=$(api_get "/projects/$(project_id)")
  if have_jq; then
    if printf '%s' "$body" | jq -e "has(\"$1\")" >/dev/null 2>&1; then
      printf '%s' "$body" | jq -r ".$1"
    else
      echo unavailable
    fi
  else
    echo unavailable
  fi
}

project_path_with_namespace() { project_field path_with_namespace; }
author_approval()             { project_field merge_requests_author_approval; }
shared_runners()              { project_field shared_runners_enabled; }

# file_action PATH — 'update' when the file is already on the main branch, 'create' otherwise.
file_action() {
  if [[ "$(api_status "/projects/$(project_id)/repository/files/$1?ref=$MAIN_BRANCH")" == "200" ]]; then
    echo update
  else
    echo create
  fi
}

# commit_fixture — commits every fixture file on the main branch, in one commit.
commit_fixture() {
  local payload status
  payload=$(mktemp)
  jq -n \
    --arg branch "$MAIN_BRANCH" \
    --arg message "Yontrack test fixture" \
    --arg ci_action "$(file_action '.gitlab-ci.yml')" \
    --rawfile ci_content "$FIXTURE_DIR/.gitlab-ci.yml" \
    --arg properties_action "$(file_action 'gradle.properties')" \
    --rawfile properties_content "$FIXTURE_DIR/gradle.properties" \
    '{
       branch: $branch,
       commit_message: $message,
       actions: [
         {action: $ci_action, file_path: ".gitlab-ci.yml", content: $ci_content},
         {action: $properties_action, file_path: "gradle.properties", content: $properties_content}
       ]
     }' > "$payload"
  status=$(api_post_status "/projects/$(project_id)/repository/commits" "$payload")
  rm -f "$payload"
  if [[ "$status" == "201" ]]; then
    ok "fixture committed on $MAIN_BRANCH"
  else
    warn "the commit failed with HTTP ${status:-nothing} — the token needs the 'api' scope and the bot needs write access"
    SKIPPED+=("the commit of the fixture content")
  fi
}

# smoke_pipeline — triggers one mock pipeline and waits for it, to prove the fixture works.
smoke_pipeline() {
  local payload response id status attempt
  payload=$(mktemp)
  jq -n --arg ref "$MAIN_BRANCH" \
    '{ref: $ref, variables: [
        {key: "MOCK_RESULT", value: "success"},
        {key: "MOCK_DURATION", value: "1"},
        {key: "MOCK_MESSAGE", value: "gitlab-test-project.sh"}
      ]}' > "$payload"
  response=$(api_post "/projects/$(project_id)/pipeline" "$payload")
  rm -f "$payload"
  id=$(printf '%s' "$response" | jq -r '.id // empty' 2>/dev/null || true)
  if [[ -z "$id" ]]; then
    warn "no pipeline was created — GitLab answered: $(printf '%s' "$response" | head -c 200)"
    SKIPPED+=("the pipeline smoke test")
    return
  fi
  ok "pipeline $id created — https://gitlab.com/$(full_path)/-/pipelines/$id"
  # 10 seconds between polls: the tests are held to the same minimum.
  for attempt in $(seq 1 30); do
    status=$(api_get "/projects/$(project_id)/pipelines/$id" | jq -r '.status // empty' 2>/dev/null || true)
    case "$status" in
      success) ok "the pipeline succeeded"; return ;;
      failed|canceled|skipped)
        warn "the pipeline ended as '$status' — open it and see why"
        SKIPPED+=("the pipeline smoke test (ended as $status)")
        return ;;
      *) printf '  %s… %s (poll %s/30)%s\n' "$DIM" "${status:-pending}" "$attempt" "$RESET"; sleep 10 ;;
    esac
  done
  warn "the pipeline was still '$status' after 5 minutes — check it in the browser"
  SKIPPED+=("the pipeline smoke test (still running)")
}

# ──────────────────────────────────────────────────────────────────────────

banner "GitLab test project"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before you start"
say "This provisions the Free gitlab.com group the real ontrack-extension-gitlab tests run"
say "against: a bot account, a group, a fixture project with its pipeline, a token and the CI secrets."
say ""
say "You will need:"
step "an email address you control for the bot account — plus-addressing works"
note "  (e.g. you+yontrack-gitlab@…)"
step "a phone and, on a new account, a payment card: gitlab.com asks for identity verification"
note "  before it lets a free namespace use the shared runners at all"
step "an authenticator app — gitlab.com requires 2FA"
step "gh, signed in with admin rights on $GH_REPO, for the secrets"
say ""
say "One account, not two: unlike Bitbucket Cloud, GitLab lets the author approve their own merge"
say "request, so no separate approver identity is needed — just a project setting, in stage 6."
say ""
for tool in curl jq gh; do
  if command -v "$tool" >/dev/null 2>&1; then ok "$tool is installed"; else warn "$tool is missing"; fi
done
if gh_ready; then ok "gh is authenticated"; else warn "gh is not authenticated — run 'gh auth login' first, or set the secrets by hand at the end"; fi
have_jq || warn "without jq the wizard cannot commit the fixture nor read the project settings"
note "Values are remembered in $ENV_FILE (gitignored)."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The bot account"
say "The bot is the identity the tests use for everything: reading, branches, merge requests,"
say "approvals and pipelines. It owns the group, which makes it the group's Owner."
open_url "https://gitlab.com/users/sign_up"
step "Sign up with the bot's email address and verify it (or sign in, if it already exists)."
step "Set up 2FA when asked — gitlab.com requires it. Keep the recovery codes."
step "Complete the identity verification (phone, and a card on a new account) if gitlab.com asks:"
note "    without it the free namespace gets no shared runner, and no pipeline ever starts."
step "Stay signed in as the bot in this window."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The group"
open_url "https://gitlab.com/groups/new"
step "Signed in as the bot: create a group, e.g. yontrack-test."
step "Visibility: Private. Plan: Free — no trial, no payment method."
note "Its path is the part after https://gitlab.com/ — that is what the wizard asks for."
require ask ONTRACK_TEST_EXTENSION_GITLAB_GROUP "Group path:"
write_env ONTRACK_TEST_EXTENSION_GITLAB_GROUP "$ONTRACK_TEST_EXTENSION_GITLAB_GROUP"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The bot's personal access token"
say "A personal access token, not a project or group access token: those are Premium on gitlab.com."
open_url "https://gitlab.com/-/user_settings/personal_access_tokens"
step "Signed in as the bot: Add new token."
step "Name: yontrack-tests."
step "Expiration date: the furthest gitlab.com offers — a token lasts 365 days at most."
step "Scope: api. It is the one scope the tests need, and it covers all of them."
step "Create, and copy the token — it is shown only once."
require ask_secret ONTRACK_TEST_EXTENSION_GITLAB_TOKEN "Personal access token:"
ask_date ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY "Its expiry date (YYYY-MM-DD):"
write_env ONTRACK_TEST_EXTENSION_GITLAB_TOKEN "$ONTRACK_TEST_EXTENSION_GITLAB_TOKEN"
write_env ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY "$ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY"
expect 200 "the token authenticates" api_status "/user"
expect 200 "the token reads the group" api_status "/groups/$(group_id)"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The fixture project"
open_url "https://gitlab.com/projects/new#blank_project"
step "In the bot's window: create a blank project."
step "Project name: yontrack-fixture. Project URL: the group from stage 3."
step "Visibility: Private."
step "Initialize repository with a README: No — the wizard commits the content in stage 8."
note "The project's path is the last part of its URL, without the group."
require ask ONTRACK_TEST_EXTENSION_GITLAB_PROJECT "Project path (without the group):"
write_env ONTRACK_TEST_EXTENSION_GITLAB_PROJECT "$ONTRACK_TEST_EXTENSION_GITLAB_PROJECT"
expect 200 "the token reads the project" api_status "/projects/$(project_id)"
expect "$(full_path)" "the project is in the group" project_path_with_namespace
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Self-approval of merge requests"
say "The auto-versioning tests have the bot approve its own merge request. GitLab allows that, but"
say "only when the project says so — this is the setting that replaces Bitbucket's second account."
open_url "https://gitlab.com/$(full_path)/-/settings/merge_requests"
step "Settings → Merge requests → Approval settings."
step "Leave 'Prevent approval by author' UNCHECKED, and save."
note "That is merge_requests_author_approval = true on the API."
pause "Done? Press Enter to check"
while true; do
  approval=$(author_approval)
  case "$approval" in
    true) ok "the bot may approve its own merge request"; break ;;
    unavailable)
      note "gitlab.com did not report merge_requests_author_approval — check the box in the UI yourself."
      break ;;
    *)
      warn "the project still prevents approval by the author (merge_requests_author_approval=$approval)"
      confirm "Fixed it — check again?" || { SKIPPED+=("merge_requests_author_approval on $(full_path)"); break; } ;;
  esac
done
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Shared runners"
say "Only the pipeline tests need a runner, and they are the only thing here that costs anything:"
say "a Free namespace gets 400 compute minutes a month."
open_url "https://gitlab.com/$(full_path)/-/settings/ci_cd"
step "Settings → CI/CD → Runners → enable 'Instance runners' for this project."
note "Nothing runs on a push: the fixture pipeline only exists when MOCK_RESULT is passed."
pause "Done? Press Enter to check"
expect true "the shared runners are enabled on the project" shared_runners
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "The fixture content"
say "The wizard commits, as the bot, on $MAIN_BRANCH:"
step ".gitlab-ci.yml — one 'mock' job, which ends as MOCK_RESULT asks after MOCK_DURATION seconds"
step "gradle.properties — the file the auto-versioning tests edit (version=…)"
note "From $FIXTURE_DIR"
note "The pipeline is created only when MOCK_RESULT is passed, so a branch the tests push runs nothing."
if ! have_jq; then
  warn "jq is missing — install it and re-run the wizard to commit the fixture"
  SKIPPED+=("the commit of the fixture content (jq is missing)")
elif [[ "$(file_action '.gitlab-ci.yml')" == "update" ]]; then
  ok "the fixture is already on $MAIN_BRANCH"
  if confirm "Commit the current fixture files again (e.g. after changing them)?"; then commit_fixture; fi
elif confirm "Commit the fixture files now?"; then
  commit_fixture
else
  SKIPPED+=("the commit of the fixture content")
fi
expect 200 ".gitlab-ci.yml is on $MAIN_BRANCH" api_status "/projects/$(project_id)/repository/files/.gitlab-ci.yml?ref=$MAIN_BRANCH"
expect 200 "gradle.properties is on $MAIN_BRANCH" api_status "/projects/$(project_id)/repository/files/gradle.properties?ref=$MAIN_BRANCH"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "The pipeline, once"
say "One mock pipeline, triggered the way the tests trigger it, proves the fixture end to end:"
say "the token may create pipelines, a runner picks the job up, and it succeeds."
warn "It costs about one compute minute out of the 400 the month has."
if ! have_jq; then
  SKIPPED+=("the pipeline smoke test (jq is missing)")
elif confirm "Run it now?"; then
  smoke_pipeline
else
  SKIPPED+=("the pipeline smoke test")
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Token expiry"
say "The token expires on ${BOLD}$ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY${RESET}, and a GitLab personal"
say "access token cannot last more than 365 days: renewing it is an annual chore, not a one-off."
if grep -q '<!-- token-expiry -->' "$README"; then
  tmp=$(mktemp)
  sed -E "s|(<!-- token-expiry -->).*(<!-- /token-expiry -->)|\1${ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY}\2|" "$README" > "$tmp"
  mv "$tmp" "$README"
  ok "README: renewal date set to $ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY"
  step "Commit ontrack-extension-gitlab/README.md once the wizard is done."
else
  warn "no token-expiry marker in $README — record $ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY there by hand"
fi
step "Put a reminder in a calendar a month before $ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY: re-run this wizard."
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "GitHub secrets"
say "The real GitLab tests read these secrets from $GH_REPO:"
for name in $SECRETS; do step "$name"; done
say "and this variable, which is no secret:"
step "$EXPIRY_VAR = $ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY"
if confirm "Write them to $GH_REPO now (existing values are replaced)?"; then
  for name in $SECRETS; do set_secret "$name" "${!name}"; done
  set_var "$EXPIRY_VAR" "$ONTRACK_TEST_EXTENSION_GITLAB_TOKEN_EXPIRY"
else
  SKIPPED+=("the GitHub secrets and the $EXPIRY_VAR variable")
fi
if gh_ready; then
  say ""
  say "GitLab secrets and variables now in $GH_REPO:"
  gh secret list | grep GITLAB | sed 's/^/    /' || true
  gh variable list | grep GITLAB | sed 's/^/    /' || true
fi
pause

finish

say "Run the real tests locally with:"
note "  set -a; source $ENV_FILE; set +a"
note "  ./gradlew :ontrack-extension-gitlab:integrationTest"
printf '\n'
