[[promotion-levels]]
=== Managing promotion levels

[[promotion-levels-auto-promotion]]
==== Auto promotion

By default, a build is <<model,promoted>> explicitly, by associated a promotion
with it.

By configuring an auto promotion, we allow a build to be automatically promoted
whenever a given list of validations or promotions have passed on this build.

For example, if a build had passed integration tests on platforms A, B and C,
we can imagine promoting automatically this build to a promotion level,
without having to do it explicitly.

In order to configure the auto promotion, go to the promotion level and set
the "Auto promotion" property. You then associate the list of validation stamps
that must have passed or promotion levels which must be granted on a build in
order to get this build automatically promoted.

NOTE: A validation is considered as having passed when the status of its last run
is `PASSED` or `FIXED` - a validation which failed and was later fixed counts
towards the auto promotion.

The list of validation stamps can be defined by:

* selecting a fixed list of validation stamps
* selecting the validation stamps based on their name, using `include` and
`exclude` regular expressions

IMPORTANT: A validation stamp defined in the list is _always_ taken into account in the
auto promotion, whatever the values for the `include` and `exclude` regular
promotions.

The list of promotion levels can be set independently of the list of validation stamps.

[[promotion-levels-checks]]
==== Promotion checks

By default, a build can be promoted to any promotion independently
of any other constraint.

In particular, promotions are ordered and a build can be promoted to a given
promotion without the previous ones being granted.

If this "lax" behavior is not correct, you can configure this in several ways, using
_promotion checks_.

NOTE: This check on previous promotions is built-in in Ontrack but other
could be added by creating <<extending-promotion-checks,extensions>>.

[[promotion-levels-checks-previous]]
===== Previous promotion check

One check is to make sure that a promotion is granted _only_ if the previous
one is granted. For example, if we have BRONZE -> SILVER -> GOLD as promotions for
a branch:

* SILVER could not be promoted if IRON is not
* GOLD could not be promoted if SILVER is not

You can activate this behaviour:

* globally, by activating the settings for "Previous promotion condition"
* at project, branch or even promotion level level, by setting and activating
the "Previous promotion condition" property

The order of priority of this check is as follows:

* promotion level "Previous promotion condition" property (takes precedence on a branch setup)
* branch "Previous promotion condition" property (takes precedence on a project setup)
* project "Previous promotion condition" property (takes precedence on global settings)
* Global "Previous promotion condition" settings

[[promotion-levels-checks-dependencies]]
===== Previous dependencies check

You can also define a set of dependencies to a promotion, like
a list of promotions which must be granted before a promotion
is itself granted.

For example, if we have IRON -> BRONZE -> SILVER -> GOLD as promotions for
a branch, we could decide that GOLD _cannot_ be promoted if either BRONZE or
SILVER is missing.

You can activate this behaviour by setting the "Promotion dependencies"
property on a promotion level, and selecting the dependencies it depends on.

[[promotion-levels-auto-creation]]
==== Auto creation

Creating the promotion levels for each branch, or making sure they are always
up to date, can be a non trivial task. Having mechanisms like cloning
can help, but then one must still make sure the list
of promotion levels in the cloned branches is
regularly synchronized to the list of targets.

Another approach is to allow projects to create automatically the promotion
levels on demand, whenever a build is promoted. This must of course be
authorized at project level and a list of predefined promotion levels must be
maintained globally.

[[promotion-levels-auto-creation-predefined]]
===== Predefined promotion levels

The management of predefined promotion levels is accessible to any
_Administrator_, in his user menu.

He can create, edit and delete predefined promotion levels, and associate
images with them.

IMPORTANT: Deleting a predefined promotion level has no impact on the ones
which were created from it in the branches. No link is kept between the
promotion levels in the branches and the predefined ones.

[[promotion-levels-auto-creation-projects]]
===== Configuring projects

By default, a project does not authorize the automatic creation of a promotion
level. In case one attempts to validate a build using a non existing promotion
level, an error would be thrown.

In order to enable this feature on a project, add the _Auto promotion levels_
property to the project and set _Auto creation_ to _Yes_.

Disabling the auto creation can be done either by setting _Auto creation_ to
_No_ or by removing the property altogether.

[[promotion-levels-auto-creation-creation]]
===== Auto creation of promotion levels

When the auto creation is enabled, build promotions using a promotion level
name will follow this procedure:

* if the promotion level is already defined in the branch, it is of course used
* if the promotion level is predefined, it is used to create a new one on the
branch and is then used
* in any other case, an error is displayed

IMPORTANT: The auto creation of promotion levels is available only through the API. It is not accessible through the GUI, where only the promotion levels of the branch can be selected for a build promotion.
