#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Provisions the Bitbucket Cloud test workspace behind the real ontrack-extension-bitbucket-cloud tests
# (issue #1755). See the "Testing" section of ontrack-extension-bitbucket-cloud/README.md.
#
#   ontrack-extension-bitbucket-cloud/scripts/bitbucket-cloud-test-workspace.sh
#
# Re-run it to renew the tokens: Enter keeps every value already captured.

TOTAL_STAGES=14

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
MODULE_DIR=$(dirname "$SCRIPT_DIR")
REPO_ROOT=$(dirname "$MODULE_DIR")
FIXTURE_DIR="$MODULE_DIR/src/test/resources/bitbucket-cloud-fixture"
README="$MODULE_DIR/README.md"
# Remembers the values between runs, and doubles as an environment file for running the real tests locally.
# Gitignored. It holds the tokens in clear: keep it on this machine.
ENV_FILE="$REPO_ROOT/.bitbucket-cloud-test.env"
# The library's gh calls carry no --repo: pin the repository whatever the current remote.
export GH_REPO="yontrack/yontrack"
API="https://api.bitbucket.org"

ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_PROJECT=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_REPOSITORY=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_EMAIL=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN_EXPIRY=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_EMAIL=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN_EXPIRY=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN=""
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN_EXPIRY=""

SECRETS="ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_PROJECT
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_REPOSITORY
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_EMAIL
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_EMAIL
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN"
EXPIRY_VAR="ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_TOKENS_EXPIRY"
DEAD_SECRETS="ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_USER
ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_TOKEN"

# ── Helpers for these stages ──────────────────────────────────────────────

ok() { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

# require ask|ask_secret KEY "Prompt" — like ask, but insists on a value.
require() {
  local fn="$1" key="$2" prompt="$3"
  while true; do
    "$fn" "$key" "$prompt"
    [[ -n "${!key}" ]] && return 0
    warn "a value is required"
  done
}

# ask_date KEY "Prompt" — insists on a YYYY-MM-DD date.
ask_date() {
  local key="$1" prompt="$2"
  while true; do
    ask "$key" "$prompt"
    [[ "${!key}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] && return 0
    warn "expected a date as YYYY-MM-DD"
  done
}

# The credentials go through curl's stdin config, never its command line, so they don't show in `ps`.

# basic_status EMAIL TOKEN PATH — HTTP status of a GET with an API token.
basic_status() {
  printf 'user = "%s:%s"\n' "$1" "$2" \
    | curl -sS -K - -o /dev/null -w '%{http_code}' "$API$3" 2>/dev/null || true
}

# basic_get EMAIL TOKEN PATH — body of a GET with an API token.
basic_get() {
  printf 'user = "%s:%s"\n' "$1" "$2" | curl -sS -K - "$API$3" 2>/dev/null || true
}

# bearer_status TOKEN PATH — HTTP status of a GET with an access token.
bearer_status() {
  printf 'header = "Authorization: Bearer %s"\n' "$1" \
    | curl -sS -K - -o /dev/null -w '%{http_code}' "$API$2" 2>/dev/null || true
}

# expect EXPECTED "what" COMMAND... — runs COMMAND until it prints EXPECTED, or the human gives up.
expect() {
  local expected="$1" what="$2" actual
  shift 2
  while true; do
    actual=$("$@")
    if [[ "$actual" == "$expected" ]]; then
      ok "$what"
      return 0
    fi
    warn "$what — got '${actual:-nothing}', expected '$expected'"
    note "A wrong value? Answer N, let the wizard finish, and re-run it: Enter keeps the other values."
    if ! confirm "Fixed it in the browser — check again?"; then
      SKIPPED+=("check failed: $what")
      return 0
    fi
  done
}

repo_path() {
  printf '/2.0/repositories/%s/%s' "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE" "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_REPOSITORY"
}

bot_status() {
  basic_status "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_EMAIL" "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN" "$1"
}

approver_status() {
  basic_status "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_EMAIL" "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN" "$1"
}

repository_project() {
  basic_get "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_EMAIL" "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN" "$(repo_path)" \
    | grep -Eo '"project": *\{[^}]*"key": *"[^"]*"' | grep -Eo '"key": *"[^"]*"' | sed -E 's/.*"([^"]*)"$/\1/' || true
}

pipelines_state() {
  if basic_get "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_EMAIL" "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN" "$(repo_path)/pipelines_config" \
    | grep -Eq '"enabled": *true'; then
    echo enabled
  else
    echo disabled
  fi
}

upload_fixture() {
  local status
  status=$(printf 'user = "%s:%s"\n' "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_EMAIL" "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN" \
    | curl -sS -K - -o /dev/null -w '%{http_code}' -X POST "$API$(repo_path)/src" \
        -F "gradle.properties=@$FIXTURE_DIR/gradle.properties" \
        -F "bitbucket-pipelines.yml=@$FIXTURE_DIR/bitbucket-pipelines.yml" \
        -F "message=Yontrack test fixture" \
        -F "branch=main" 2>/dev/null || true)
  if [[ "$status" == "201" ]]; then
    ok "fixture committed on main"
  else
    warn "upload failed with HTTP ${status:-nothing} — the bot token needs write:repository:bitbucket"
    SKIPPED+=("upload of the fixture content")
  fi
}

# ──────────────────────────────────────────────────────────────────────────

banner "Bitbucket Cloud test workspace"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before you start"
say "This provisions the Free Bitbucket Cloud workspace the real ontrack-extension-bitbucket-cloud"
say "tests run against: a bot, an approver, a fixture repository, three tokens and the CI secrets."
say ""
say "You will need:"
step "two email addresses you control, one per Atlassian account — plus-addressing works"
note "  (e.g. you+yontrack-bot@… and you+yontrack-approver@…)"
step "a second browser profile or a private window, to be signed in as both accounts at once"
step "gh, signed in with admin rights on $GH_REPO, for the secrets"
say ""
for tool in curl gh; do
  if command -v "$tool" >/dev/null 2>&1; then ok "$tool is installed"; else warn "$tool is missing"; fi
done
if gh_ready; then ok "gh is authenticated"; else warn "gh is not authenticated — run 'gh auth login' first, or set the secrets by hand at the end"; fi
note "Values are remembered in $ENV_FILE (gitignored)."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The bot account"
say "The bot is the identity the tests use for everything: reading, branches, pull requests, pipelines."
say "It is a plain Atlassian account, and it creates the workspace, which makes it the workspace admin."
open_url "https://bitbucket.org/account/signup/"
step "Sign up with the bot's email address and verify it (or sign in, if it already exists)."
step "Stay signed in as the bot in this window."
require ask ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_EMAIL "Bot email address:"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_EMAIL "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_EMAIL"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The workspace"
open_url "https://bitbucket.org/account/workspaces/"
step "Signed in as the bot: Create workspace."
step "Name it for the tests (e.g. yontrack-test). Its ID is the slug in https://bitbucket.org/<ID>/."
step "Private, and the Free plan — no trial, no payment method."
note "Free: 5 users, 50 build minutes a month. The bot and the approver take two users."
require ask ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE "Workspace ID:"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The bot's API token"
open_url "https://id.atlassian.com/manage-profile/security/api-tokens"
step "Signed in as the bot: Create API token with scopes."
step "Name: yontrack-tests. Expires on: the latest date offered (one year at most). Next."
step "App: Bitbucket. Next."
step "Scopes, then Next and Create token:"
note "    read:user:bitbucket         read:workspace:bitbucket     read:project:bitbucket"
note "    read:repository:bitbucket   write:repository:bitbucket"
note "    read:pullrequest:bitbucket  write:pullrequest:bitbucket"
note "    read:pipeline:bitbucket     write:pipeline:bitbucket"
step "Copy the token — it is shown only once."
require ask_secret ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN "Bot API token:"
ask_date ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN_EXPIRY "Its expiry date (YYYY-MM-DD):"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN_EXPIRY "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN_EXPIRY"
expect 200 "the bot's token authenticates" bot_status "/2.0/user"
expect 200 "the bot reads the workspace's repositories" bot_status "/2.0/repositories/$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The approver account"
say "Bitbucket does not let a user approve their own pull request: auto-versioning auto-approval"
say "needs a second identity to approve the bot's pull requests."
step "In a private window or another browser profile, open https://bitbucket.org/account/signup/"
step "Sign up the approver with its own email address and verify it."
require ask ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_EMAIL "Approver email address:"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_EMAIL "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_EMAIL"
say ""
say "Now, in the bot's window, invite the approver to the workspace:"
open_url "https://bitbucket.org/$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE/workspace/settings/"
step "Workspace settings → User management → Invite → the approver's email address."
step "In the approver's window, accept the invitation from the email."
pause "Approver invited and accepted? Press Enter"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The approver's API token"
step "In the approver's window, open https://id.atlassian.com/manage-profile/security/api-tokens"
step "Create API token with scopes. Name: yontrack-tests. Expires on: the latest date offered. Next."
step "App: Bitbucket. Next."
step "Scopes, then Next and Create token:"
note "    read:user:bitbucket  read:repository:bitbucket  read:pullrequest:bitbucket  write:pullrequest:bitbucket"
step "Copy the token — it is shown only once."
require ask_secret ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN "Approver API token:"
ask_date ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN_EXPIRY "Its expiry date (YYYY-MM-DD):"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN_EXPIRY "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN_EXPIRY"
expect 200 "the approver's token authenticates" approver_status "/2.0/user"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The fixture repository"
open_url "https://bitbucket.org/$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE/workspace/create/repository"
step "In the bot's window, create the repository (Create → Repository, if the page above does not open it):"
step "Project: create a new one, e.g. name Yontrack, key YONTRACK."
step "Repository name: yontrack-fixture. Private."
step "Include a README: No. Include .gitignore: No. Default branch name: main."
note "The wizard commits the content itself in two stages' time."
require ask ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_PROJECT "Project key:"
require ask ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_REPOSITORY "Repository slug (the last part of its URL):"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_PROJECT "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_PROJECT"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_REPOSITORY "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_REPOSITORY"
expect 200 "the bot reads the repository" bot_status "$(repo_path)"
expect "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_PROJECT" "the repository is in the project" repository_project
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "The approver's access to the repository"
open_url "https://bitbucket.org/$(repo_path | sed 's|^/2.0/repositories/||')/admin/permissions"
step "In the bot's window: Repository settings → Repository permissions → Add users."
step "The approver, with Write."
pause "Done? Press Enter to check"
expect 200 "the approver reads the repository" approver_status "$(repo_path)"
expect 200 "the approver reads its pull requests" approver_status "$(repo_path)/pullrequests"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "The fixture content"
say "The wizard commits, as the bot, on main:"
step "gradle.properties — the file the auto-versioning tests edit (version=…)"
step "bitbucket-pipelines.yml — custom pipelines only: yontrack-echo, yontrack-fail, yontrack-auto-versioning"
note "From $FIXTURE_DIR"
note "No default pipeline: nothing runs when the tests push, which keeps the 50 minutes for pipeline tests."
if [[ "$(bot_status "$(repo_path)/src/main/bitbucket-pipelines.yml")" == "200" ]]; then
  ok "the fixture is already on main"
  if confirm "Commit the current fixture files again (e.g. after changing them)?"; then upload_fixture; fi
elif confirm "Commit the fixture files now?"; then
  upload_fixture
else
  SKIPPED+=("upload of the fixture content")
fi
expect 200 "gradle.properties is on main" bot_status "$(repo_path)/src/main/gradle.properties"
expect 200 "bitbucket-pipelines.yml is on main" bot_status "$(repo_path)/src/main/bitbucket-pipelines.yml"
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Bitbucket Pipelines"
open_url "https://bitbucket.org/$(repo_path | sed 's|^/2.0/repositories/||')/admin/pipelines/settings"
step "In the bot's window: Repository settings → Pipelines → Settings → Enable Pipelines."
note "Only custom pipelines exist: nothing runs until a test triggers one."
pause "Enabled? Press Enter to check"
expect enabled "Pipelines are enabled" pipelines_state
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "The repository access token"
say "The Bearer identity (ACCESS_TOKEN configurations). Every plan has repository access tokens;"
say "workspace and project access tokens need Premium."
open_url "https://bitbucket.org/$(repo_path | sed 's|^/2.0/repositories/||')/admin/access-tokens"
step "In the bot's window: Repository settings → Security → Access tokens → Create access token."
step "Name: yontrack-tests. Expiry: the latest date offered (No expiry, if the workspace allows it)."
step "Permissions:"
note "    Repositories: Read, Write"
note "    Pull requests: Read, Write"
note "    Pipelines: Read, Write"
step "Create, and copy the token — it is shown only once."
require ask_secret ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN "Repository access token:"
ask_date ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN_EXPIRY "Its expiry date (YYYY-MM-DD; 9999-12-31 for No expiry):"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN"
write_env ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN_EXPIRY "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN_EXPIRY"
expect 200 "the access token reads the repository" bearer_status "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN" "$(repo_path)"
expect 200 "the access token reads the pull requests" bearer_status "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN" "$(repo_path)/pullrequests"
expect 200 "the access token reads the pipelines" bearer_status "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN" "$(repo_path)/pipelines/"
pause

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Token expiry"
TOKENS_EXPIRY=$(printf '%s\n' \
  "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_BOT_TOKEN_EXPIRY" \
  "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_APPROVER_TOKEN_EXPIRY" \
  "$ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_ACCESS_TOKEN_EXPIRY" | sort | sed -n 1p)
write_env "$EXPIRY_VAR" "$TOKENS_EXPIRY"
say "The first token to expire does so on ${BOLD}$TOKENS_EXPIRY${RESET}."
say "From two weeks before that date, BitbucketCloudTestWorkspaceIT fails and asks for a renewal."
if grep -q '<!-- tokens-expiry -->' "$README"; then
  tmp=$(mktemp)
  sed -E "s|(<!-- tokens-expiry -->).*(<!-- /tokens-expiry -->)|\1${TOKENS_EXPIRY}\2|" "$README" > "$tmp"
  mv "$tmp" "$README"
  ok "README: renewal date set to $TOKENS_EXPIRY"
  step "Commit ontrack-extension-bitbucket-cloud/README.md once the wizard is done."
else
  warn "no tokens-expiry marker in $README — record $TOKENS_EXPIRY there by hand"
fi
step "Put a reminder in a calendar a month before $TOKENS_EXPIRY: re-run this wizard."
pause

# ── 13 ────────────────────────────────────────────────────────────────────
stage "GitHub secrets"
say "The integration shard of .github/workflows/ci.yml reads these secrets from $GH_REPO:"
for name in $SECRETS; do step "$name"; done
say "and this variable, which is no secret:"
step "$EXPIRY_VAR = $TOKENS_EXPIRY"
if confirm "Write them to $GH_REPO now (existing values are replaced)?"; then
  for name in $SECRETS; do set_secret "$name" "${!name}"; done
  set_var "$EXPIRY_VAR" "$TOKENS_EXPIRY"
else
  SKIPPED+=("GitHub secrets and the $EXPIRY_VAR variable")
fi
pause

# ── 14 ────────────────────────────────────────────────────────────────────
stage "Retire the app-password secrets"
say "Atlassian removed app passwords on 2026-07-28. These secrets hold one and nothing reads them any more:"
for name in $DEAD_SECRETS; do step "$name"; done
note "ONTRACK_TEST_EXTENSION_BITBUCKET_CLOUD_WORKSPACE stays: the previous stage replaced its value."
if gh_ready; then
  printf '  %sDeleting a secret cannot be undone.%s\n' "$RED" "$RESET"
  if confirm "Delete these two secrets from $GH_REPO?"; then
    for name in $DEAD_SECRETS; do
      if gh secret delete "$name" >/dev/null 2>&1; then ok "deleted $name"; else warn "could not delete $name (already gone?)"; fi
    done
  else
    SKIPPED+=("deletion of the app-password secrets: gh secret delete <name>")
  fi
  say ""
  say "Bitbucket Cloud secrets and variables now in $GH_REPO:"
  gh secret list | grep BITBUCKET_CLOUD | sed 's/^/    /' || true
  gh variable list | grep BITBUCKET_CLOUD | sed 's/^/    /' || true
else
  SKIPPED+=("deletion of the app-password secrets: gh secret delete <name>")
fi
pause

finish

say "Run the real tests locally with:"
note "  set -a; source $ENV_FILE; set +a"
note "  ./gradlew :ontrack-extension-bitbucket-cloud:integrationTest"
say "In CI, dispatch the CI workflow with SKIP_BITBUCKET_CLOUD_IT unticked."
printf '\n'
