package net.nemerosa.ontrack.extension.findings.ingestion

import io.micrometer.core.instrument.MeterRegistry
import net.nemerosa.ontrack.extension.findings.metrics.FindingsMetrics
import net.nemerosa.ontrack.extension.findings.repository.FindingRepository
import net.nemerosa.ontrack.extension.findings.validation.FindingsValidationDataType
import net.nemerosa.ontrack.extension.general.validation.CHML
import net.nemerosa.ontrack.extension.general.validation.CHMLLevel
import net.nemerosa.ontrack.extension.general.validation.CHMLValidationDataTypeConfig
import net.nemerosa.ontrack.graphql.AbstractQLKTITSupport
import net.nemerosa.ontrack.json.parseAsJson
import net.nemerosa.ontrack.model.structure.Branch
import net.nemerosa.ontrack.model.structure.Build
import net.nemerosa.ontrack.model.structure.ValidationStamp
import net.nemerosa.ontrack.model.structure.config
import org.junit.jupiter.api.Test
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Autowired
import tools.jackson.databind.JsonNode
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.time.measureTimedValue

/**
 * Ingestion of a large SARIF report through the door, `validateBuildWithFindings`, to keep its
 * duration under watch.
 *
 * The durations are logged, never asserted: timings are not reliable in CI. The threshold which
 * matters is the p95 of the `ontrack_findings_ingestion` timer on `self.dev.yontrack.com`, see
 * `doc/dev-guide/findings-ingestion.md`.
 *
 * The report is generated by the test, rather than stored as a 5 MB fixture.
 */
class FindingsIngestionPerformanceIT : AbstractQLKTITSupport() {

    private val logger: Logger = LoggerFactory.getLogger(FindingsIngestionPerformanceIT::class.java)

    @Autowired
    private lateinit var findingsValidationDataType: FindingsValidationDataType

    @Autowired
    private lateinit var findingRepository: FindingRepository

    @Autowired
    private lateinit var meterRegistry: MeterRegistry

    @Test
    fun `Ingesting a 5 MB SARIF report, first with new findings, then with known ones`() {
        val sarif = generateSarif(minSize = FIVE_MB)
        assertTrue(sarif.text.length >= FIVE_MB, "The report is at least 5 MB")

        val (report, parsing) = measureTimedValue { sarif.text.parseAsJson() }
        logger.info(
            "[findings][performance] SARIF report of {} bytes, {} results, {} findings, read as JSON in {}",
            sarif.text.length, sarif.results, sarif.findings, parsing
        )

        val summaryCountBefore = summaryCount()

        asAdmin {
            project {
                branch {
                    val vs = findingsStamp()

                    // First scan: every finding is new
                    val first = build()
                    val (firstRun, firstDuration) = measureTimedValue { first.validate(vs, report) }
                    logger.info(
                        "[findings][performance] First ingestion, {} new findings: {}",
                        sarif.findings, firstDuration
                    )

                    // Second scan: every finding is known
                    val second = build()
                    val (secondRun, secondDuration) = measureTimedValue { second.validate(vs, report) }
                    logger.info(
                        "[findings][performance] Second ingestion, {} known findings: {}",
                        sarif.findings, secondDuration
                    )

                    // What was written, not how fast
                    assertEquals(sarif.findings, findingRepository.findFindingsByProject(project.id()).size)
                    listOf(firstRun, secondRun).forEach { run ->
                        assertEquals(
                            sarif.findings,
                            findingRepository.findObservationsByValidationRun(run.path("id").asInt()).size
                        )
                    }
                    assertEquals(
                        sarif.findings,
                        findingRepository.findExposuresByBranchAndStamp(id(), vs.id()).size
                    )
                }
            }
        }

        // Both ingestions are recorded
        assertEquals(summaryCountBefore + 2, summaryCount())
    }

    private fun summaryCount(): Long =
        meterRegistry.find(FindingsMetrics.ingestionFindings)
            .tag(FindingsMetrics.Tags.FORMAT, "sarif")
            .summary()?.count() ?: 0

    private fun Branch.findingsStamp(): ValidationStamp =
        validationStamp(
            validationDataTypeConfig = findingsValidationDataType.config(
                CHMLValidationDataTypeConfig(
                    warningLevel = CHMLLevel(CHML.HIGH, 1),
                    failedLevel = CHMLLevel(CHML.CRITICAL, 1),
                )
            )
        )

    private fun Build.validate(vs: ValidationStamp, report: JsonNode): JsonNode =
        assertNoUserError(
            run(
                """
                    mutation Validate(
                        ${'$'}project: String!,
                        ${'$'}branch: String!,
                        ${'$'}build: String!,
                        ${'$'}validation: String!,
                        ${'$'}report: JSON!,
                    ) {
                        validateBuildWithFindings(input: {
                            project: ${'$'}project,
                            branch: ${'$'}branch,
                            build: ${'$'}build,
                            validation: ${'$'}validation,
                            format: "sarif",
                            kind: CODE,
                            report: ${'$'}report,
                        }) {
                            validationRun {
                                id
                            }
                            errors {
                                message
                                exception
                            }
                        }
                    }
                """,
                mapOf(
                    "project" to vs.project.name,
                    "branch" to vs.branch.name,
                    "build" to name,
                    "validation" to vs.name,
                    "report" to report,
                )
            ),
            "validateBuildWithFindings"
        ).path("validationRun")

    /**
     * Generated SARIF report.
     *
     * @property text JSON text of the report
     * @property results Number of results in the report
     * @property findings Number of distinct findings in the report: rule and file
     */
    private class GeneratedSarif(
        val text: String,
        val results: Int,
        val findings: Int,
    )

    /**
     * Generates a CodeQL-like SARIF report, with rules carrying their descriptions and security
     * severities, and results with messages, regions and fingerprints, until the report is at
     * least [minSize] characters long. Each finding — a rule in a file — is reported twice, at
     * two different lines, as a scanner does for the same issue in two places of a file.
     */
    private fun generateSarif(minSize: Int): GeneratedSarif {
        val s = StringBuilder(minSize + 64 * 1024)
        s.append("""{"${'$'}schema":"https://json.schemastore.org/sarif-2.1.0.json","version":"2.1.0","runs":[{""")
        s.append(""""tool":{"driver":{"name":"CodeQL","organization":"GitHub","semanticVersion":"2.16.4","rules":[""")
        (0 until RULES).forEach { rule ->
            if (rule > 0) s.append(',')
            val score = 1.0 + (rule % 90) / 10.0
            s.append(
                """{"id":"java/rule-$rule","name":"java/rule-$rule",""" +
                        """"shortDescription":{"text":"Rule number $rule of the generated report"},""" +
                        """"fullDescription":{"text":"Full description of the rule number $rule, long enough to look like the description of a real query of a real scanner."},""" +
                        """"defaultConfiguration":{"enabled":true,"level":"error"},""" +
                        """"helpUri":"https://codeql.github.com/codeql-query-help/java/java-rule-$rule/",""" +
                        """"properties":{"tags":["security","external/cwe/cwe-${rule + 100}"],"kind":"problem","precision":"high","security-severity":"$score"}}"""
            )
        }
        s.append("]}},")
        s.append(""""results":[""")
        var results = 0
        while (s.length < minSize) {
            if (results > 0) s.append(',')
            // Two results per finding
            val finding = results / 2
            val file = finding % FILES
            val rule = (finding / FILES) % RULES
            val line = 10 + (results % 2) * 100 + file % 50
            s.append(
                """{"ruleId":"java/rule-$rule","ruleIndex":$rule,"level":"error",""" +
                        """"message":{"text":"This expression depends on a user-provided value, found by the rule $rule in the file $file at line $line."},""" +
                        """"locations":[{"physicalLocation":{"artifactLocation":{"uri":"src/main/java/com/example/module${file % 20}/Component$file.java","uriBaseId":"%SRCROOT%"},""" +
                        """"region":{"startLine":$line,"startColumn":12,"endColumn":48}}}],""" +
                        """"partialFingerprints":{"primaryLocationLineHash":"${"%016x".format(results.toLong() * 2654435761L)}:1"}}"""
            )
            results++
        }
        s.append("]}]}")
        val findings = (0 until results).map { it / 2 }.distinct().size
        return GeneratedSarif(text = s.toString(), results = results, findings = findings)
    }

    companion object {
        private const val FIVE_MB = 5 * 1024 * 1024
        private const val RULES = 50
        private const val FILES = 2_000
    }
}
