import {gql} from "graphql-request";
import {graphQLCallMutation} from "@ontrack/graphql";

/**
 * Registers an agent owned by the current user, with a token.
 *
 * @param ontrack Client acting as the owner of the agent
 * @param slug Slug of the agent, generated by default
 * @param displayName Display name of the agent
 * @param tool Tool behind the agent
 * @return The agent `{id, email, displayName, tool, token, client}`, where `client(session)` returns
 * a client acting as the agent, with the agent session headers when `session` is given as
 * `{id, link}`.
 */
export const registerAgent = async (ontrack, {
    slug = `ui-agent-${Date.now().toString(36)}-${Math.floor(Math.random() * 1000)}`,
    displayName = `Agent ${slug}`,
    tool = "Claude Code",
} = {}) => {
    const registration = await graphQLCallMutation(
        ontrack.connection,
        'registerAgent',
        gql`
            mutation RegisterAgent($slug: String!, $displayName: String!, $tool: String!) {
                registerAgent(input: {slug: $slug, displayName: $displayName, tool: $tool}) {
                    errors {
                        message
                    }
                    agent {
                        id
                        email
                    }
                }
            }
        `,
        {slug, displayName, tool}
    )
    const {id, email} = registration.registerAgent.agent

    const generation = await graphQLCallMutation(
        ontrack.connection,
        'generateAgentToken',
        gql`
            mutation GenerateAgentToken($id: Int!, $name: String!) {
                generateAgentToken(input: {id: $id, name: $name}) {
                    errors {
                        message
                    }
                    token {
                        value
                    }
                }
            }
        `,
        {id: Number(id), name: "ui"}
    )
    const token = generation.generateAgentToken.token.value

    return {
        id,
        email,
        displayName,
        tool,
        token,
        client: (session) => ontrack.withToken(
            token,
            session ? {
                'X-Yontrack-Agent-Session': session.id,
                ...(session.link ? {'X-Yontrack-Agent-Session-Link': session.link} : {}),
            } : {}
        ),
    }
}
