mutation UpdateEstate(
    $id: Int!,
    $name: String!,
    $description: String,
    $labels: [String!]!,
    $marker: EstateMarkerInput,
    $readings: [EstateReadingConfigInput!],
    $security: EstateSecurityInput,
) {
    updateEstate(input: {
        id: $id,
        name: $name,
        description: $description,
        labels: $labels,
        marker: $marker,
        readings: $readings,
        security: $security,
    }) {
        ...PayloadUserErrors
        estate {
            ...EstateFragment
        }
    }
}
