-- #2025 Agents: the actor on the record

-- 1. Every signer column takes an account identifier as long as ACCOUNTS.EMAIL: an email longer
--    than 40 characters could not sign until now

ALTER TABLE BUILDS
    ALTER COLUMN CREATOR TYPE VARCHAR(200);
ALTER TABLE PROMOTION_RUNS
    ALTER COLUMN CREATOR TYPE VARCHAR(200);
ALTER TABLE VALIDATION_RUN_STATUSES
    ALTER COLUMN CREATOR TYPE VARCHAR(200);
ALTER TABLE EVENTS
    ALTER COLUMN EVENT_USER TYPE VARCHAR(200);

ALTER TABLE ENV_SLOT_PIPELINE_CHANGE
    ALTER COLUMN "USER" TYPE VARCHAR(200);
ALTER TABLE ENV_SLOT_PIPELINE_ADMISSION_RULE_STATUS
    ALTER COLUMN DATA_USER TYPE VARCHAR(200),
    ALTER COLUMN OVERRIDE_USER TYPE VARCHAR(200);
ALTER TABLE ENV_SLOT_WORKFLOW_INSTANCES
    ALTER COLUMN "USER" TYPE VARCHAR(200);

ALTER TABLE PROJECTS
    ALTER COLUMN CREATOR TYPE VARCHAR(200);
ALTER TABLE BRANCHES
    ALTER COLUMN CREATOR TYPE VARCHAR(200);
ALTER TABLE PROMOTION_LEVELS
    ALTER COLUMN CREATOR TYPE VARCHAR(200);
ALTER TABLE VALIDATION_STAMPS
    ALTER COLUMN CREATOR TYPE VARCHAR(200);
ALTER TABLE RUN_INFO
    ALTER COLUMN CREATOR TYPE VARCHAR(200);
ALTER TABLE ENTITY_DATA_STORE
    ALTER COLUMN CREATOR TYPE VARCHAR(200);
ALTER TABLE ENTITY_DATA_STORE_AUDIT
    ALTER COLUMN CREATOR TYPE VARCHAR(200);

-- 2. The actor of a signature, when it is an agent - NULL is a person, and there is no backfill:
--    {"kind": "agent", "agent": "<slug>[agent]", "displayName": ..., "tool": ..., "owner": "<email>", "session": {"id": ..., "link": ...}}
--    The names are copied, so that they survive the deletion of the agent.

ALTER TABLE BUILDS
    ADD COLUMN ACTOR JSONB NULL;
ALTER TABLE PROMOTION_RUNS
    ADD COLUMN ACTOR JSONB NULL;
ALTER TABLE VALIDATION_RUN_STATUSES
    ADD COLUMN ACTOR JSONB NULL;
ALTER TABLE EVENTS
    ADD COLUMN ACTOR JSONB NULL;
ALTER TABLE ENV_SLOT_PIPELINE_CHANGE
    ADD COLUMN ACTOR JSONB NULL;

-- 3. The events of an agent

CREATE INDEX EVENTS_IX_ACTOR_AGENT ON EVENTS ((ACTOR ->> 'agent')) WHERE ACTOR IS NOT NULL;
