-- 105. Security findings: periods of the exposure (#2040)
--
-- An exposure row is the current state of a finding on a branch for a stamp, and a reopening
-- overwrites it. Its periods are kept here, one row per stretch from the first run which reported
-- the finding to the first run which no longer did, with the runs and the display names of their
-- builds: a purged build takes its run, its name stays.
--
-- Times are stored as VARCHAR(24), in the Time.forStorage format, as in every other table.

CREATE TABLE FINDING_EXPOSURE_PERIODS
(
    ID                           SERIAL PRIMARY KEY NOT NULL,
    FINDING_ID                   INTEGER            NOT NULL,
    BRANCH_ID                    INTEGER            NOT NULL,
    VALIDATION_STAMP_ID          INTEGER            NOT NULL,
    STARTED_AT                   VARCHAR(24)        NOT NULL,
    STARTED_BY_VALIDATION_RUN_ID INTEGER            NULL,
    STARTED_IN_BUILD             VARCHAR(255)       NULL,
    ENDED_AT                     VARCHAR(24)        NULL,
    ENDED_BY_VALIDATION_RUN_ID   INTEGER            NULL,
    ENDED_IN_BUILD               VARCHAR(255)       NULL,
    RESOLUTION_REASON            VARCHAR(20)        NULL, -- ABSENT
    CONSTRAINT FINDING_EXPOSURE_PERIODS_FK_FINDING FOREIGN KEY (FINDING_ID) REFERENCES FINDINGS (ID) ON DELETE CASCADE,
    CONSTRAINT FINDING_EXPOSURE_PERIODS_FK_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID) ON DELETE CASCADE,
    CONSTRAINT FINDING_EXPOSURE_PERIODS_FK_VALIDATION_STAMP FOREIGN KEY (VALIDATION_STAMP_ID) REFERENCES VALIDATION_STAMPS (ID) ON DELETE CASCADE,
    CONSTRAINT FINDING_EXPOSURE_PERIODS_FK_STARTED_BY FOREIGN KEY (STARTED_BY_VALIDATION_RUN_ID) REFERENCES VALIDATION_RUNS (ID) ON DELETE SET NULL,
    CONSTRAINT FINDING_EXPOSURE_PERIODS_FK_ENDED_BY FOREIGN KEY (ENDED_BY_VALIDATION_RUN_ID) REFERENCES VALIDATION_RUNS (ID) ON DELETE SET NULL
);

-- At most one open period per exposure
CREATE UNIQUE INDEX FINDING_EXPOSURE_PERIODS_UQ_OPEN
    ON FINDING_EXPOSURE_PERIODS (FINDING_ID, BRANCH_ID, VALIDATION_STAMP_ID)
    WHERE ENDED_AT IS NULL;
CREATE INDEX FINDING_EXPOSURE_PERIODS_IX_KEY
    ON FINDING_EXPOSURE_PERIODS (FINDING_ID, BRANCH_ID, VALIDATION_STAMP_ID, STARTED_AT);
CREATE INDEX FINDING_EXPOSURE_PERIODS_IX_STARTED_BY ON FINDING_EXPOSURE_PERIODS (STARTED_BY_VALIDATION_RUN_ID);
CREATE INDEX FINDING_EXPOSURE_PERIODS_IX_ENDED_BY ON FINDING_EXPOSURE_PERIODS (ENDED_BY_VALIDATION_RUN_ID);

-- The existing exposures, before their periods were kept: one period each, from its start to its
-- resolution, if any, with no run and no build
INSERT INTO FINDING_EXPOSURE_PERIODS (FINDING_ID, BRANCH_ID, VALIDATION_STAMP_ID, STARTED_AT, ENDED_AT, RESOLUTION_REASON)
SELECT FINDING_ID, BRANCH_ID, VALIDATION_STAMP_ID, SINCE, RESOLVED_AT, RESOLUTION_REASON
FROM FINDING_EXPOSURES;
