-- Configurable fields on promotion levels
-- Field definitions are stored per promotion level
CREATE TABLE PROMOTION_LEVEL_FIELDS
(
    ID                 SERIAL PRIMARY KEY NOT NULL,
    PROMOTION_LEVEL_ID INTEGER            NOT NULL,
    NAME               VARCHAR(100)       NOT NULL,
    DISPLAY_NAME       VARCHAR(200)       NOT NULL,
    DESCRIPTION        VARCHAR(500),
    FIELD_TYPE         VARCHAR(20)        NOT NULL, -- TEXT | NUMBER | BOOLEAN | CHOICE
    REQUIRED           BOOLEAN            NOT NULL DEFAULT FALSE,
    OPTIONS            JSONB,                       -- non-null only for CHOICE: ["opt1","opt2",...]
    POSITION           INTEGER            NOT NULL DEFAULT 0,
    CONSTRAINT PROMOTION_LEVEL_FIELDS_FK
        FOREIGN KEY (PROMOTION_LEVEL_ID) REFERENCES PROMOTION_LEVELS (ID) ON DELETE CASCADE
);
CREATE INDEX PROMOTION_LEVEL_FIELDS_IDX ON PROMOTION_LEVEL_FIELDS (PROMOTION_LEVEL_ID);

-- Field values are stored per promotion run
CREATE TABLE PROMOTION_RUN_FIELD_VALUES
(
    ID               SERIAL PRIMARY KEY NOT NULL,
    PROMOTION_RUN_ID INTEGER            NOT NULL,
    FIELD_NAME       VARCHAR(100)       NOT NULL,
    FIELD_VALUE      JSONB,             -- null = optional field not filled; typed JSON otherwise
    CONSTRAINT PROMOTION_RUN_FIELD_VALUES_FK
        FOREIGN KEY (PROMOTION_RUN_ID) REFERENCES PROMOTION_RUNS (ID) ON DELETE CASCADE
);
CREATE INDEX PROMOTION_RUN_FIELD_VALUES_IDX ON PROMOTION_RUN_FIELD_VALUES (PROMOTION_RUN_ID);
