-- 83. Security findings (#1855)
--
-- The vocabulary is the one of CONTEXT.md: a finding, its observations and its exposure.
--
-- Times are stored as VARCHAR(24), in the Time.forStorage format, as in every other table.

-- A finding: one known weakness at one location of one project.
-- It references the project only, so that it survives the purge of the builds which observed it.
CREATE TABLE FINDINGS
(
    ID           SERIAL PRIMARY KEY NOT NULL,
    PROJECT_ID   INTEGER            NOT NULL,
    SCANNER      VARCHAR(100)       NOT NULL,
    EXTERNAL_ID  VARCHAR(255)       NOT NULL,
    LOCATION     VARCHAR(1024)      NOT NULL, -- may be empty, never null
    KIND         VARCHAR(20)        NOT NULL, -- IMAGE | CODE | SECRETS | DAST | DEPENDENCIES | OTHER
    TITLE        TEXT               NOT NULL,
    URL          TEXT               NULL,
    FIRST_SEEN   VARCHAR(24)        NOT NULL,
    LAST_SEEN    VARCHAR(24)        NOT NULL,
    RESOLVED_AT  VARCHAR(24)        NULL,
    MAX_SEVERITY VARCHAR(10)        NOT NULL, -- CRITICAL | HIGH | MEDIUM | LOW | UNKNOWN
    CONSTRAINT FINDINGS_FK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX FINDINGS_UQ_KEY ON FINDINGS (PROJECT_ID, SCANNER, EXTERNAL_ID, LOCATION);
CREATE INDEX FINDINGS_IX_PROJECT ON FINDINGS (PROJECT_ID);
CREATE INDEX FINDINGS_IX_EXTERNAL_ID ON FINDINGS (EXTERNAL_ID);

-- An observation: one sighting of a finding by one scan (validation run) of one build.
-- It goes with its validation run, and therefore with its build.
CREATE TABLE FINDING_OBSERVATIONS
(
    ID                    SERIAL PRIMARY KEY NOT NULL,
    FINDING_ID            INTEGER            NOT NULL,
    VALIDATION_RUN_ID     INTEGER            NOT NULL,
    OBSERVED_AT           VARCHAR(24)        NOT NULL,
    SEVERITY              VARCHAR(10)        NOT NULL, -- CRITICAL | HIGH | MEDIUM | LOW | UNKNOWN
    RAW_SEVERITY          VARCHAR(100)       NULL,
    INSTALLED_VERSION     VARCHAR(255)       NULL,
    FIXED_VERSION         VARCHAR(255)       NULL,
    ACCEPTED              BOOLEAN            NOT NULL DEFAULT FALSE,
    ACCEPTANCE_STATEMENT  TEXT               NULL,
    ACCEPTANCE_EXPIRES_AT DATE               NULL,
    ACCEPTANCE_SOURCE     VARCHAR(500)       NULL,
    CONSTRAINT FINDING_OBSERVATIONS_FK_FINDING FOREIGN KEY (FINDING_ID) REFERENCES FINDINGS (ID) ON DELETE CASCADE,
    CONSTRAINT FINDING_OBSERVATIONS_FK_VALIDATION_RUN FOREIGN KEY (VALIDATION_RUN_ID) REFERENCES VALIDATION_RUNS (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX FINDING_OBSERVATIONS_UQ_RUN_FINDING ON FINDING_OBSERVATIONS (VALIDATION_RUN_ID, FINDING_ID);
CREATE INDEX FINDING_OBSERVATIONS_IX_FINDING ON FINDING_OBSERVATIONS (FINDING_ID);

-- An exposure: a finding is exposed on a branch while the latest scan of the same stamp on
-- that branch reports it. A deleted branch (or stamp) takes its exposure rows with it.
CREATE TABLE FINDING_EXPOSURES
(
    ID                  SERIAL PRIMARY KEY NOT NULL,
    FINDING_ID          INTEGER            NOT NULL,
    BRANCH_ID           INTEGER            NOT NULL,
    VALIDATION_STAMP_ID INTEGER            NOT NULL,
    SINCE               VARCHAR(24)        NOT NULL,
    CONSTRAINT FINDING_EXPOSURES_FK_FINDING FOREIGN KEY (FINDING_ID) REFERENCES FINDINGS (ID) ON DELETE CASCADE,
    CONSTRAINT FINDING_EXPOSURES_FK_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (ID) ON DELETE CASCADE,
    CONSTRAINT FINDING_EXPOSURES_FK_VALIDATION_STAMP FOREIGN KEY (VALIDATION_STAMP_ID) REFERENCES VALIDATION_STAMPS (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX FINDING_EXPOSURES_UQ_KEY ON FINDING_EXPOSURES (FINDING_ID, BRANCH_ID, VALIDATION_STAMP_ID);
CREATE INDEX FINDING_EXPOSURES_IX_BRANCH_STAMP ON FINDING_EXPOSURES (BRANCH_ID, VALIDATION_STAMP_ID);
CREATE INDEX FINDING_EXPOSURES_IX_VALIDATION_STAMP ON FINDING_EXPOSURES (VALIDATION_STAMP_ID);
