-- 87. Search documents partitioned by type (#1888)
--
-- A search reads each type on its own, in the order of its ranking - tier, then most recently
-- updated - and stops at the cap of the counts, so that a frequent word never has all its matches
-- read. On one table, that meant searching the full-text and trigram indexes once per type, each
-- search going through the entries of every type. Partitioned by type, each type has indexes of
-- its own: reading a type on its own costs what one search of the whole table used to.
--
-- Hash partitions, and not one list partition per type: the types come from the indexers of the
-- extensions, and would otherwise need DDL at startup. Two types may share a partition, which
-- then serves both.
--
-- The search documents are derived data: the table is created again, empty, and every type is
-- rebuilt at the next startup - which forgetting their rebuild status below triggers. 6.0 creates
-- the table (V85), so no released version holds documents that this drops.
DROP TABLE SEARCH_DOCUMENTS;

-- Same columns as V85. The primary key includes the partition key, as Postgres requires.
CREATE TABLE SEARCH_DOCUMENTS
(
    ID          SERIAL             NOT NULL,
    TYPE        VARCHAR(100)       NOT NULL,
    KEY         TEXT               NOT NULL,
    PROJECT_ID  INTEGER            NULL,
    ENTITY_TYPE VARCHAR(40)        NULL,
    ENTITY_ID   INTEGER            NULL,
    TITLE       TEXT               NOT NULL,
    IDENTIFIERS TEXT               NOT NULL,
    TEXT        TEXT               NULL,
    TSV         TSVECTOR GENERATED ALWAYS AS (
        setweight(to_tsvector('simple'::regconfig, TITLE), 'A') ||
        setweight(to_tsvector('simple'::regconfig, IDENTIFIERS), 'A') ||
        setweight(to_tsvector('simple'::regconfig, coalesce(TEXT, '')), 'C')
        ) STORED,
    DATA        JSONB              NOT NULL,
    UPDATED_AT  TIMESTAMP          NOT NULL,
    INDEXED_AT  TIMESTAMP          NOT NULL,
    CONSTRAINT SEARCH_DOCUMENTS_PK PRIMARY KEY (TYPE, ID),
    CONSTRAINT SEARCH_DOCUMENTS_UQ_TYPE_KEY UNIQUE (TYPE, KEY),
    CONSTRAINT SEARCH_DOCUMENTS_FK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID) ON DELETE CASCADE
) PARTITION BY HASH (TYPE);

CREATE TABLE SEARCH_DOCUMENTS_P00 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE SEARCH_DOCUMENTS_P01 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE SEARCH_DOCUMENTS_P02 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE SEARCH_DOCUMENTS_P03 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE SEARCH_DOCUMENTS_P04 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE SEARCH_DOCUMENTS_P05 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE SEARCH_DOCUMENTS_P06 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE SEARCH_DOCUMENTS_P07 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE SEARCH_DOCUMENTS_P08 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE SEARCH_DOCUMENTS_P09 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE SEARCH_DOCUMENTS_P10 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE SEARCH_DOCUMENTS_P11 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE SEARCH_DOCUMENTS_P12 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE SEARCH_DOCUMENTS_P13 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE SEARCH_DOCUMENTS_P14 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE SEARCH_DOCUMENTS_P15 PARTITION OF SEARCH_DOCUMENTS FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- The indexes of V85 and V86, created on every partition
CREATE INDEX SEARCH_DOCUMENTS_IX_TSV ON SEARCH_DOCUMENTS USING GIN (TSV);
CREATE INDEX SEARCH_DOCUMENTS_IX_IDENTIFIERS_TRGM ON SEARCH_DOCUMENTS USING GIN (IDENTIFIERS gin_trgm_ops);
CREATE INDEX SEARCH_DOCUMENTS_IX_TITLE_TRGM ON SEARCH_DOCUMENTS USING GIN (TITLE gin_trgm_ops);
CREATE INDEX SEARCH_DOCUMENTS_IX_TITLE_PREFIX ON SEARCH_DOCUMENTS (lower(TITLE) text_pattern_ops);
CREATE INDEX SEARCH_DOCUMENTS_IX_TYPE_PROJECT ON SEARCH_DOCUMENTS (TYPE, PROJECT_ID);
CREATE INDEX SEARCH_DOCUMENTS_IX_PROJECT ON SEARCH_DOCUMENTS (PROJECT_ID);
CREATE INDEX SEARCH_DOCUMENTS_IX_ENTITY ON SEARCH_DOCUMENTS (ENTITY_TYPE, ENTITY_ID);
-- The matches of a type, most recently updated first
CREATE INDEX SEARCH_DOCUMENTS_IX_TYPE_RECENCY ON SEARCH_DOCUMENTS (TYPE, UPDATED_AT DESC, ID);

-- Every type is rebuilt at the next startup
DELETE FROM STORAGE WHERE STORE = 'net.nemerosa.ontrack.service.search.SearchDocumentStartupRebuild';
