package net.nemerosa.ontrack.extension.audittrail.endorsement

import net.nemerosa.ontrack.model.security.AbstractConfidentialStore
import org.junit.jupiter.api.Test
import java.time.Duration
import java.util.concurrent.ConcurrentHashMap
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The instance key over the stores it can meet: writable, read-only, unreachable, or holding
 * something else than a key.
 */
class InstanceKeyServiceImplTest {

    private val hash = "4b320b3f1628780eaf5adbc9153975aa05eeb25fd082f97b111588499a6550a6"

    /**
     * A store in memory, like the file, JDBC and Vault stores.
     */
    private open class MemoryStore : AbstractConfidentialStore() {
        val keys = ConcurrentHashMap<String, ByteArray>()
        var stores = 0
        override fun store(key: String, payload: ByteArray) {
            stores++
            keys[key] = payload
        }

        override fun load(key: String): ByteArray? = keys[key]
    }

    /**
     * A store which refuses writes, like the `secret` store.
     */
    private class ReadOnlyStore : MemoryStore() {
        override fun store(key: String, payload: ByteArray) {
            throw IllegalStateException("Read-only store")
        }
    }

    @Test
    fun `The key is generated on first use, stored, and endorses the entries`() {
        val store = MemoryStore()
        val service = InstanceKeyServiceImpl(store)

        val endorsement = service.endorse(hash)

        assertNotNull(endorsement)
        val stored = assertNotNull(store.keys[InstanceKeyServiceImpl.STORE_KEY])
        val key = InstanceKey.parse(stored)
        assertEquals(key.keyId, endorsement.keyId)
        assertTrue(TrailEndorsementFormat.verify(key.publicKey, hash, endorsement.signature))
        assertEquals(InstanceKeyStatus.OK, service.keyStatus)
        assertEquals(
            listOf(InstancePublicKey(key.keyId, "Ed25519", key.publicKeyPem)),
            service.getPublicKeys()
        )
    }

    @Test
    fun `The key is stored under audit-trail ed25519`() {
        assertEquals("audit-trail.ed25519", InstanceKeyServiceImpl.STORE_KEY)
    }

    @Test
    fun `The stored key is used, and never replaced`() {
        val store = MemoryStore()
        val existing = InstanceKey.generate()
        store.keys[InstanceKeyServiceImpl.STORE_KEY] = existing.toPkcs8()

        val service = InstanceKeyServiceImpl(store)

        assertEquals(existing.keyId, service.endorse(hash)?.keyId)
        assertEquals(InstanceKeyStatus.OK, service.keyStatus)
        assertEquals(0, store.stores, "Nothing stored")
        assertContentEquals(existing.toPkcs8(), store.keys[InstanceKeyServiceImpl.STORE_KEY])
    }

    @Test
    fun `The key generated by a first service is the key of the next one`() {
        val store = MemoryStore()
        val first = InstanceKeyServiceImpl(store).endorse(hash)?.keyId
        val second = InstanceKeyServiceImpl(store).endorse(hash)?.keyId
        assertNotNull(first)
        assertEquals(first, second)
        assertEquals(1, store.stores, "Generated once")
    }

    @Test
    fun `Asking for the key status generates the key`() {
        val store = MemoryStore()
        assertEquals(InstanceKeyStatus.OK, InstanceKeyServiceImpl(store).keyStatus)
        assertNotNull(store.keys[InstanceKeyServiceImpl.STORE_KEY])
    }

    @Test
    fun `Listing the public keys does not generate the key`() {
        val store = MemoryStore()
        assertEquals(emptyList(), InstanceKeyServiceImpl(store).getPublicKeys())
        assertNull(store.keys[InstanceKeyServiceImpl.STORE_KEY])
    }

    @Test
    fun `Without a key in a read-only store, nothing is endorsed and the key is reported as not provisioned`() {
        val service = InstanceKeyServiceImpl(ReadOnlyStore())
        assertNull(service.endorse(hash))
        assertEquals(InstanceKeyStatus.NOT_PROVISIONED, service.keyStatus)
        assertEquals(emptyList(), service.getPublicKeys())
    }

    @Test
    fun `A key provisioned in a read-only store is found without a restart`() {
        val store = ReadOnlyStore()
        val service = InstanceKeyServiceImpl(store)
        service.retryInterval = Duration.ZERO
        assertNull(service.endorse(hash))

        val provisioned = InstanceKey.generate()
        store.keys[InstanceKeyServiceImpl.STORE_KEY] = provisioned.toPkcs8()

        assertEquals(provisioned.keyId, service.endorse(hash)?.keyId)
        assertEquals(InstanceKeyStatus.OK, service.keyStatus)
    }

    @Test
    fun `A store which is not available is not asked again before the retry interval`() {
        var loads = 0
        val store = object : MemoryStore() {
            override fun load(key: String): ByteArray? {
                loads++
                throw IllegalStateException("Store not available")
            }
        }
        val service = InstanceKeyServiceImpl(store)
        assertNull(service.endorse(hash))
        assertNull(service.endorse(hash))
        assertEquals(InstanceKeyStatus.NOT_PROVISIONED, service.keyStatus)
        assertEquals(1, loads, "Store asked once within the retry interval")
        assertEquals(0, store.stores, "No key generated when the store cannot be read")
    }

    @Test
    fun `A stored payload which is not a key is reported, and never replaced`() {
        val store = MemoryStore()
        store.keys[InstanceKeyServiceImpl.STORE_KEY] = "not a key".toByteArray()
        val service = InstanceKeyServiceImpl(store)

        assertNull(service.endorse(hash))
        assertEquals(InstanceKeyStatus.NOT_PROVISIONED, service.keyStatus)
        assertEquals(0, store.stores, "Not replaced")
    }
}
